---

- name: Add apt keys
  apt_key:
    data: "{{ lookup('file', item) }}"
  with_fileglob:
    - "apt_keys/*"

- name: install sshd
  apt: update_cache=yes name=openssh-server state=latest

- name: configure sshd
  copy: src=sshd_config dest=/etc/ssh/sshd_config mode=0755
  notify: restart sshd

- name: install haproxy
  apt: name=haproxy state=latest

- name: init add script
  copy: src=haproxy-add dest=/usr/local/bin/haproxy-add mode=0755

- name: init del script
  copy: src=haproxy-del dest=/usr/local/bin/haproxy-del mode=0755

- name: configure haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: start haproxy
  service: name=haproxy state=started enabled=yes
