---

- name: install packages
  apt: name={{ item}} update_cache=yes 
  with_items:
    - "tftpd-hpa"
    - "nginx"
    - "isc-dhcp-server" 
    - "syslinux"

- name: get net inst
  unarchive:
    src: http://mirror.yandex.ru/debian/dists/stretch/main/installer-amd64/current/images/netboot/netboot.tar.gz
    dest: /srv/tftp
    remote_src: yes

- name: copy modules
  copy: 
    src: "{{ item }}"  
    dest: /srv/tftp
    remote_src: yes
  with_items:
    - "/usr/lib/syslinux/modules/bios/ldlinux.c32"
    - "/usr/lib/syslinux/modules/bios/libcom32.c32"
    - "/usr/lib/syslinux/modules/bios/libutil.c32"
    - "/usr/lib/syslinux/modules/bios/menu.c32"
    
- name: configure isc-dhcp-server
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf
  notify: restart isc-dhcp-server

- name: create pxe dir
  file:
    path: /export/pxe
    state: directory
    mode: 0755

- name: configure ngnix
  template: src=nginx.cfg.j2 dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: add preseed
  template: src=deb-pres.cfg.j2 dest=/export/pxe/deb-pres.cfg
  notify: restart nginx

- name: delete symb link
  file:
    path: /srv/tftp/pxelinux.cfg
    state: absent

- name: delete symb links
  command: cp -r {{ item }} /srv/tftp
  with_items:
    - "/srv/tftp/debian-installer/amd64/pxelinux.0"
    - "/srv/tftp/debian-installer/amd64/pxelinux.cfg"

- name: configure pxe
  template: src=pxe.cfg.j2 dest=/srv/tftp/pxelinux.cfg/default

