#!/bin/bash +H
# made by: KorG

# app will listen on this port on every instance VM
PORT=8080
FILE=/etc/haproxy/haproxy.cfg

: "${1:?specify IP}"

panic(){ echo "$*" >&2 ; exit 2; }

egrep -q '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' <<<"$1" ||
	panic invalid IP

fgrep "$1" "$FILE" && panic IP is already exists

sed -i.bak "/^backend/a\\
	server srv${RANDOM}${RANDOM} $1:$PORT check" "$FILE" &&
service haproxy restart &&
fgrep -q "$1" "$FILE"
