#!/bin/bash +H
# made by: KorG

# app will listen on this port on every instance VM
PORT=8080
FILE=/etc/haproxy/haproxy.cfg

: "${1:?specify IP}"

panic(){ echo "$*" >&2 ; exit 2; }

egrep -q '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' <<<"$1" ||
	panic invalid IP

fgrep -q "$1" "$FILE" || panic IP not found in "$FILE"

sed -i.bak "/server.*$1:$PORT check/d" "$FILE" &&
service haproxy restart &&
! fgrep -q "$1" "$FILE"
